### ISSUE TITLE
Testing ember cdv:serve for Windows Apps

### ISSUE THREAD

**Issue by joshuairl** [isleofcode/corber#316]
```
$ ember cdv:s --proxy=https://api-v2.my-app.com --platform=windows --environment=development
Your ember-cordova/cordova/config.xml file has set thefollowing flag:
        <allow-navigation href="*" />
This is necessary for device live-reload to work,
but is unsafe and should not be used in production.

The format of cordova.raw.* methods "options" argument was changed in 5.4.0. "options.options" property now should be an object instead of an array of plain strings. Though the old format is still supported, consider updating your cordova.raw.* method ca
lls to use new argument format.
The following navigation rule had an invalid URI scheme and will be ignored: "*".
Building project: C:\Users\170510\Projects\my-app\ember-cordova\cordova\platforms\windows\CordovaApp.Windows10.jsproj
        Configuration : debug
        Platform      : anycpu
  CordovaApp.Windows10 -> C:\Users\170510\Projects\my-app\ember-cordova\cordova\platforms\windows\AppPackages\CordovaApp.Windows10_1.0.0.0_anycpu_debug_Test\CordovaApp.Windows10_1.0.0.0_anycpu_debug.appx
DEPRECATION: Addon files were detected in `C:/Users/170510/Projects/my-app/node_modules/ember-cordova/addon`, but no JavaScript preprocessors were found for `ember-cordova`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) t
o in `dependencies` (NOT `devDependencies`) in `ember-cordova`'s `package.json`.
DEPRECATION: Addon files were detected in `C:/Users/170510/Projects/my-app/node_modules/ember-load-initializers/addon`, but no JavaScript preprocessors were found for `ember-load-initializers`. Please make sure to add a preprocessor (most likely
`ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `ember-load-initializers`'s `package.json`.
ERROR: ember-cordova
TypeError: Path must be a string. Received undefined
Error: ERROR: ember-cordova
TypeError: Path must be a string. Received undefined
    at Object.error (C:\Users\170510\Projects\my-app\node_modules\ember-cordova\lib\utils\logger.js:21:11)
    at C:\Users\170510\Projects\my-app\node_modules\ember-cordova\lib\commands\serve.js:148:14
    at tryCatch (C:\Users\170510\Projects\my-app\node_modules\rsvp\dist\rsvp.js:539:12)
    at invokeCallback (C:\Users\170510\Projects\my-app\node_modules\rsvp\dist\rsvp.js:554:13)
    at publish (C:\Users\170510\Projects\my-app\node_modules\rsvp\dist\rsvp.js:522:7)
    at publishRejection (C:\Users\170510\Projects\my-app\node_modules\rsvp\dist\rsvp.js:457:3)
    at flush (C:\Users\170510\Projects\my-app\node_modules\rsvp\dist\rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

The error I'm investigating is:
`ERROR: ember-cordova`
`TypeError: Path must be a string. Received undefined`

**Comment by joshuairl** [comment]
Thought it may have been the "rootURL" in the environment config.... but it's set to ''
```javascript
var ENV = {
    modulePrefix: 'my-app',
    environment: environment,
    rootURL: '',
    locationType: 'hash',
    //....
}
```

**Comment by joshuairl** [comment]
Also, should be noted - `ember cdv:build --platform=windows --environment=production` works fine.

**Comment by alexblom** [comment]
Thanks for reporting here. What version are you running on? Explicitly it would be helpful to see whats on lib\commands\serve.js:148.

I've openly not tested for Windows apps (we prefer Electron) but there is no reason it should not work.

**Comment by joshuairl** [comment]
@alexblom I don't believe Electron works on Xbox?  Or does it?

**Comment by joshuairl** [comment]
https://github.com/isleofcode/ember-cordova/blob/0.4.6/lib/commands/serve.js#L148 @ @ #

**Comment by joshuairl** [comment]
Just updated to 0.4.10 and still same error, unfortunately.
Also I did just find this:
https://github.com/felixrieseberg/electron-windows-store

Sounds intriguing... wondering if it'll work for my project.

**Comment by alexblom** [comment]
Just getting back to this. Are you attempting to do builds on windows or mac - I understand your target platform is Windows. I'll try and build a replicate case if it is still a problem.
