### ISSUE TITLE
ember-browserify compatibility

### ISSUE THREAD

**Issue by oskarrough** [isleofcode/corber#384]
Hi, running `corber serve` fails on a project that uses ember-browserify. As the app works outside corber I thought I'd open here. Let me know if I should open an issue on ember-browserify instead :)

https://github.com/ef4/ember-browserify/blob/master/lib/stubs.js#L114

```
The Broccoli Plugin: [object Object] failed with:
Error: Error parsing code while looking for "npm:" imports: TypeError: Cannot read property 'elements' of undefined
    at findAMDImports (/Users/oskar/Sites/test/node_modules/ember-browserify/lib/stubs.js:114:6)
    at /Users/oskar/Sites/test/node_modules/ember-browserify/lib/stubs.js:97:7
    at forEachNode (/Users/oskar/Sites/test/node_modules/ember-browserify/lib/stubs.js:74:5)
    at forEachNode (/Users/oskar/Sites/test/node_modules/ember-browserify/lib/stubs.js:77:7)
    at forEachNode (/Users/oskar/Sites/test/node_modules/ember-browserify/lib/stubs.js:77:7)
    at forEachNode (/Users/oskar/Sites/test/node_modules/ember-browserify/lib/stubs.js:77:7)
    at forEachNode (/Users/oskar/Sites/test/node_modules/ember-browserify/lib/stubs.js:77:7)
    at forEachNode (/Users/oskar/Sites/test/node_modules/ember-browserify/lib/stubs.js:77:7)
    at forEachNode (/Users/oskar/Sites/test/node_modules/ember-browserify/lib/stubs.js:77:7)
    at forEachNode (/Users/oskar/Sites/test/node_modules/ember-browserify/lib/stubs.js:77:7)
    at importsFor (/Users/oskar/Sites/test/node_modules/ember-browserify/lib/stubs.js:67:11)
    at Stub.set (/Users/oskar/Sites/test/node_modules/ember-browserify/lib/stubs.js:31:25)
    at StubGenerator.<anonymous> (/Users/oskar/Sites/test/node_modules/ember-browserify/lib/stub-generator.js:57:33)
    at Array.forEach (<anonymous>)
    at StubGenerator.build (/Users/oskar/Sites/test/node_modules/ember-browserify/lib/stub-generator.js:49:12)
    at /Users/oskar/Sites/test/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/Users/oskar/Sites/test/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/oskar/Sites/test/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/oskar/Sites/test/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/Users/oskar/Sites/test/node_modules/rsvp/dist/rsvp.js:2415:5)
```

**Comment by alexblom** [comment]
Thanks for the report. I don't use browserify a whole lot, can you suggest a minimum replicate case I can create on my side?

**Comment by OakBehringer** [comment]
Hey, it's your new best friend, chiming in on this one. I can confirm this is an issue - but only with ember serve. Browserify totally works with corber build. This is very easy to reproduce:
```
mkdir poop && cd poop 
ember init
(update environment.js, remove slash and set to hash)
corber init
corber add platform ios
corber build && corber open
```
yay it works!

`corber s`

yay live reload works!

```
ctrl+c
ember install ember-browserify
corber s
```

And you arrive at the error above. But build still works, which is very nice for me. 

![image](https://user-images.githubusercontent.com/2909414/32184278-0790a018-bd59-11e7-9de7-4cba7d0ca688.png)

Browserify is pretty popular, so you're likely to hear more about this, as this awesome project gains popularity. 

I'm now in Ember's slack (OakBehringer) if you have any Q's. 

Best,
Adam

**Comment by OakBehringer** [comment]
Hey Alex, you should probably mark this as closed:

https://github.com/ef4/ember-browserify

Browserify is deprecated. ember-auto-import works with Corber. Yay!

**Comment by alexblom** [comment]
Thanks for the heads up - closing.
