### ISSUE TITLE
process is not captured

### ISSUE THREAD

**Issue by yashprit** [isleofcode/corber#391]
I am using corber with ember js project
`
"corber": "1.1.3"
`
when running `corber build` it give me error `process is not captured`, below is stack trace of 

```
corber build  
                                                                    
corber: Building app
EmberCordovaError: process is not captured
    at Object.addHandler (<project-path>/node_modules/corber/node_modules/ember-cli/lib/utilities/will-interrupt-process.js:81:13)
    at new Builder <project-path>//node_modules/corber/node_modules/ember-cli/lib/models/builder.js:37:30)
    at Class.initBuilder (<project-path>//node_modules/corber/lib/frameworks/ember/tasks/build.js:15:12)
    at Class.run (/node_modules/corber/lib/frameworks/ember/tasks/build.js:24:36)
    at Class.build (<project-path>/node_modules/corber/lib/frameworks/ember/framework.js:62:23)
    at hook.run.then.then.then (/usr/local/lib/node_modules/corber/lib/commands/build.js:85:28)
    at tryCatcher (/usr/local/lib/node_modules/corber/node_modules/rsvp/dist/rsvp.js:329:19)
    at invokeCallback (/usr/local/lib/node_modules/corber/node_modules/rsvp/dist/rsvp.js:507:31)
    at publish (/usr/local/lib/node_modules/corber/node_modules/rsvp/dist/rsvp.js:493:7)
    at flush (/usr/local/lib/node_modules/corber/node_modules/rsvp/dist/rsvp.js:2432:5)
{     at Object.addHandler (<project-path>/node_modules/corber/node_modules/ember-cli/lib/utilities/will-interrupt-process.js:81:13)
    at new Builder (/node_modules/corber/node_modules/ember-cli/lib/models/builder.js:37:30)
    at Class.initBuilder (/node_modules/corber/lib/frameworks/ember/tasks/build.js:15:12)
    at Class.run (/node_modules/corber/lib/frameworks/ember/tasks/build.js:24:36)
    at Class.build (/node_modules/corber/lib/frameworks/ember/framework.js:62:23)
    at hook.run.then.then.then (/usr/local/lib/node_modules/corber/lib/commands/build.js:85:28)
    at tryCatcher (/usr/local/lib/node_modules/corber/node_modules/rsvp/dist/rsvp.js:329:19)
    at invokeCallback (/usr/local/lib/node_modules/corber/node_modules/rsvp/dist/rsvp.js:507:31)
    at publish (/usr/local/lib/node_modules/corber/node_modules/rsvp/dist/rsvp.js:493:7)
    at flush (/usr/local/lib/node_modules/corber/node_modules/rsvp/dist/rsvp.js:2432:5)
  name: 'EmberCordovaError',
  message: 'EmberCordovaError: process is not captured',
  stack: '    at Object.addHandler (node_modules/corber/node_modules/ember-cli/lib/utilities/will-interrupt-process.js:81:13)\n    at new Builder (node_modules/corber/node_modules/ember-cli/lib/models/builder.js:37:30)\n    at Class.initBuilder (node_modules/corber/lib/frameworks/ember/tasks/build.js:15:12)\n    at Class.run (/node_modules/corber/lib/frameworks/ember/tasks/build.js:24:36)\n    at Class.build (/node_modules/corber/lib/frameworks/ember/framework.js:62:23)\n    at hook.run.then.then.then (/usr/local/lib/node_modules/corber/lib/commands/build.js:85:28)\n    at tryCatcher (/usr/local/lib/node_modules/corber/node_modules/rsvp/dist/rsvp.js:329:19)\n    at invokeCallback (/usr/local/lib/node_modules/corber/node_modules/rsvp/dist/rsvp.js:507:31)\n    at publish (/usr/local/lib/node_modules/corber/node_modules/rsvp/dist/rsvp.js:493:7)\n    at flush (/usr/local/lib/node_modules/corber/node_modules/rsvp/dist/rsvp.js:2432:5)' }
```

I saw [this release](https://github.com/isleofcode/corber/releases/tag/1.1.2) which talks about it.

**Comment by alexblom** [comment]
Can you confirm for me that both your global & project package.json versions of corber are updated?

Thanks!

**Comment by yashprit** [comment]
@alexblom Yes both are `1.1.3`, I guess while running `corber init` corber itself add that project level dependencies

**Comment by Aaronfischer** [comment]
I am also experiencing this issue as well on `1.1.3`. 
Upgraded from `ember-cordova`.

(Using `npm` instead of `yarn` is that matters.)

**Comment by alexblom** [comment]
Should be resolved as of latest release. The issue would have been coming from the latest version of ember-cli. 

Let me know if you are having further troubles, will leave this open just in case.

**Comment by codebruder** [comment]
Unfortunately not. 
Failed with following setup: 
cover `1.1.4`
ember `2.15.1`
npm `5.5.1`
node `6.10.2`

Same global and project versions.

**Comment by alexblom** [comment]
Thanks to @codebruder for the remote debug, the last remaining case was captured.
