### ISSUE TITLE
Can't build with 1.2.0

### ISSUE THREAD

**Issue by hoboman313** [isleofcode/corber#457]
$ corber build --platform=android --environment=production --release
path.js:28
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'path', 'string');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.join (path.js:499:7)
    at Object.<anonymous> (E:\Projects\huegasm-premium\android\node_modules\corber\lib\targets\android\tasks\list-emulators.js:4:30)    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)

**Comment by alexblom** [comment]
Thanks for the report. Just to confirm - windows?

**Comment by hoboman313** [comment]
yep

**Comment by d8vjork** [comment]
Same here with corber init command

**Comment by alexblom** [comment]
I can see the cause of the issue, will be working on a fix later today. In the interim, downgrading from 1.2.0 should be adequate for Windows envs.
