### ISSUE TITLE
Corber: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by MatthewPringle** [isleofcode/corber#511]
Created new / empty Ember App which build fine

Added Corber, followed instructions about targets etc...

corber build --platform=android --environment=development

I get this "Corber: Path must be a string. Received undefined"

ember-cli: 3.2.0
node: 8.11.3
os: darwin x64

**Comment by alexblom** [comment]
This has been fully resolved as of 1.3.0

**Comment by lougreenwood** [comment]
Not sure if this is related, but I'm getting this error:

```
Build failed.
Build Error (ConfigReplace)

The "path" argument must be of type string. Received type object

Stack Trace and Error Report: /var/folders/h_/f56g1wf92dsbyl2hpl47djlw0000gn/T/error.dump.14e1bc8e3f3343de9c5ecdd617312cc9.log
Corber: Command failed: ember build
Command failed: ember build
```

environemnt:
```
ember: 3.3.0
ember-cli: 3.3.0
node: 10.4.1
os: darwin x64
corber: 1.3.0
```


Stack Trace and Error Report: /var/folders/h_/f56g1wf92dsbyl2hpl47djlw0000gn/T/error.dump.fe3a607c1f2bc7942c0dce50c4add99f.log
```

Error log:
```
ENV Summary:

  TIME: Mon Jul 23 2018 08:45:14 GMT+0100 (Western European Summer Time)
  TITLE: corber
  ARGV:
  - /usr/local/Cellar/node/10.4.1/bin/node
  - /usr/local/bin/corber
  - build
  EXEC_PATH: /usr/local/Cellar/node/10.4.1/bin/node
  TMPDIR: /var/folders/h_/f56g1wf92dsbyl2hpl47djlw0000gn/T
  SHELL: /bin/bash
  PATH:
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/go/bin
  - /usr/local/MacGPG2/bin
  - /Library/Frameworks/Mono.framework/Versions/Current/Commands
  PLATFORM: darwin x64
  FREEMEM: 3337654272
  TOTALMEM: 34359738368
  UPTIME: 1367400
  LOADAVG: 2.12890625,2.25390625,2.16650390625
  CPUS:
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.14.0
  - cldr: 33.0
  - http_parser: 2.8.0
  - icu: 61.1
  - modules: 64
  - napi: 3
  - nghttp2: 1.32.0
  - node: 10.4.1
  - openssl: 1.1.0h
  - tz: 2018c
  - unicode: 10.0
  - uv: 1.20.3
  - v8: 6.7.288.45-node.7
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Command failed: ember build
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Command failed: ember build
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: Command failed: ember build
    at checkExecSyncError (child_process.js:603:11)
    at Object.execSync (child_process.js:640:13)
    at Class.BashTask.runCommand (/Users/Lou/Sites/prog/node_modules/corber/lib/tasks/bash.js:30:16)
    at /Users/Lou/Sites/prog/node_modules/corber/lib/tasks/bash.js:23:12
    at initializePromise (/Users/Lou/Sites/prog/node_modules/corber/node_modules/rsvp/dist/rsvp.js:520:5)
    at new Promise (/Users/Lou/Sites/prog/node_modules/corber/node_modules/rsvp/dist/rsvp.js:995:33)
    at Class.run (/Users/Lou/Sites/prog/node_modules/corber/lib/tasks/bash.js:17:12)
    at Class.run (/Users/Lou/Sites/prog/node_modules/corber/lib/tasks/bash-build.js:22:18)
    at Class.build (/Users/Lou/Sites/prog/node_modules/corber/lib/frameworks/ember/framework.js:71:18)
    at hook.run.then.then.then (/Users/Lou/.config/yarn/global/node_modules/corber/lib/commands/build.js:90:30)
    at tryCatcher (/Users/Lou/.config/yarn/global/node_modules/corber/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/Lou/.config/yarn/global/node_modules/corber/node_modules/rsvp/dist/rsvp.js:495:31)
    at publish (/Users/Lou/.config/yarn/global/node_modules/corber/node_modules/rsvp/dist/rsvp.js:481:7)
    at flush (/Users/Lou/.config/yarn/global/node_modules/corber/node_modules/rsvp/dist/rsvp.js:2402:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)


=================================================================================
```

**Comment by lougreenwood** [comment]
Actually, I'm also getting this error on `ember build` - so likely not Corber specific...

**Comment by gersonfa** [comment]
> Actually, I'm also getting this error on `ember build` - so likely not Corber specific...

Hey, could you please guide how you resolve the issue?
