### ISSUE TITLE
corber add plugin with variables not working

### ISSUE THREAD

**Issue by OakBehringer** [isleofcode/corber#548]
`corber plugin add cordova-plugin-facebook4 --variable APP_ID=1234567890 --variable APP_NAME=SomeApp`

Result:

```
Corber: Variable(s) missing (use: --variable APP_ID=value --variable APP_NAME=value).
Variable(s) missing (use: --variable APP_ID=value --variable APP_NAME=value).


Stack Trace and Error Report: /var/folders/3k/dyt4l2qs141cnldh6ptydmq40000gn/T/error.dump.a7e2efcea00e16cdacef896bbf0f7dbd.log
```

Error report:

```
=================================================================================

ENV Summary:

  TIME: Thu Oct 18 2018 18:32:45 GMT-0700 (PDT)
  TITLE: corber
  ARGV:
  - /usr/local/Cellar/node@6/6.10.0/bin/node
  - /usr/local/bin/corber
  - plugin
  - add
  - cordova-plugin-facebook4
  - --variable
  - APP_ID=1234567890
  - --variable
  - APP_NAME=SomeApp
  EXEC_PATH: /usr/local/Cellar/node@6/6.10.0/bin/node
  TMPDIR: /var/folders/3k/dyt4l2qs141cnldh6ptydmq40000gn/T
  SHELL: /bin/bash
  PATH:
  - /usr/local/opt/node@6/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /Users/AK/.composer/vendor/bin
  - /Applications/MySQLWorkbench.app/Contents/MacOS
  PLATFORM: darwin x64
  FREEMEM: 896118784
  TOTALMEM: 17179869184
  UPTIME: 95476
  LOADAVG: 2.1259765625,1.58349609375,1.35302734375
  CPUS:
  - Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz - 2700
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - http_parser: 2.7.0
  - icu: 58.2
  - modules: 48
  - node: 6.10.0
  - openssl: 1.0.2k
  - uv: 1.9.1
  - v8: 5.1.281.93
  - zlib: 1.2.8

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Variable(s) missing (use: --variable APP_ID=value --variable APP_NAME=value).
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Variable(s) missing (use: --variable APP_ID=value --variable APP_NAME=value).
  - name: CordovaError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: CordovaError: Variable(s) missing (use: --variable APP_ID=value --variable APP_NAME=value).
    at Object.mergeVariables (/usr/local/lib/node_modules/corber/node_modules/cordova-lib/src/cordova/plugin/util.js:77:15)
    at /usr/local/lib/node_modules/corber/node_modules/cordova-lib/src/cordova/plugin/add.js:104:40
    at _fulfilled (/usr/local/lib/node_modules/corber/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/corber/node_modules/cordova-lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/corber/node_modules/cordova-lib/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/corber/node_modules/cordova-lib/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/corber/node_modules/cordova-lib/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

=================================================================================
```

Quoting the variables doesn't help (nor should it).

**Comment by OakBehringer** [comment]
Corber is 1.3.2

**Comment by alexblom** [comment]
Well that one was embarrassing - fixed on master. We're otherwise planning a release for later today.

**Comment by alexblom** [comment]
1.3.3 is now live with these fixes

**Comment by OakBehringer** [comment]
Thanks Alex!
