### ISSUE TITLE
Error when trying to add Android Platform

### ISSUE THREAD

**Issue by sdelrue** [isleofcode/corber#569]
I'm getting this error when tyring to add the android platform (on windows):

```
WARNING: Node v10.15.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js. See https://git.io/v7S5n for details.
Preparing to add platform android
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\Steven Delrue\AppData\Roaming\npm\node_modules\corber\bin\cordova-lib-runner ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```
Corber init works fine & it's a new ember project, no changes have been made in the code. 
I can create a plain phonegap project & run it on Android, so the Android-sdk is setup properly

Ember : v3.6.1
Node: 10.15.0

**Comment by ahmacleod** [comment]
@sdelrue Thanks for reporting this. We've located the issue and will be merging a fix soon.
