### ISSUE TITLE
Bug - "corber platform add ios" not working

### ISSUE THREAD

**Issue by caiokawasaki** [isleofcode/corber#607]
Sometimes When I try to add ios platform I just get this:

[https://youtu.be/87GL86vHN5A](https://youtu.be/87GL86vHN5A)

Here is the error log:

 ```
 TIME: Thu Apr 11 2019 15:51:55 GMT-0300 (Brasilia Standard Time)
  TITLE: corber
  ARGV:
  - /usr/local/Cellar/node/11.6.0/bin/node
  - /usr/local/bin/corber
  - start
  EXEC_PATH: /usr/local/Cellar/node/11.6.0/bin/node
  TMPDIR: /var/folders/_7/j7wlkb6s18n83x_rp5nptlbr0000gn/T
  SHELL: /bin/bash
  PATH:
  - /Applications/MAMP/bin/php/php7.2.1/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /Users/caiokawasaki/www/invenio-live/invenio-live-app/node_modules/.bin
  - /Users/caiokawasaki/.composer/vendor/bin
  - /Users/caiokawasaki/Library/Android/sdk/
  - /Users/caiokawasaki/Library/Android/sdk/tools
  - /Users/caiokawasaki/Library/Android/sdk/platform-tools
  PLATFORM: darwin x64
  FREEMEM: 184791040
  TOTALMEM: 8589934592
  UPTIME: 17956
  LOADAVG: 2.11474609375,2.37255859375,3.40576171875
  CPUS:
  - Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz - 2600
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - cldr: 34.0
  - http_parser: 2.8.0
  - icu: 63.1
  - llhttp: 1.0.1
  - modules: 67
  - napi: 3
  - nghttp2: 1.34.0
  - node: 11.6.0
  - openssl: 1.1.0j
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.24.1
  - v8: 7.0.276.38-node.13
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: No platforms installed. Install a platform using

        corber platform add <ios|android>

before running "corber start".

  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: No platforms installed. Install a platform using

        corber platform add <ios|android>

before running "corber start".

  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: No platforms installed. Install a platform using

        corber platform add <ios|android>

before running "corber start".

    at getPlatforms.then (/usr/local/lib/node_modules/corber/lib/commands/start.js:80:15)
    at tryCatcher (/usr/local/lib/node_modules/corber/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/usr/local/lib/node_modules/corber/node_modules/rsvp/dist/rsvp.js:495:31)
    at /usr/local/lib/node_modules/corber/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/usr/local/lib/node_modules/corber/node_modules/rsvp/dist/rsvp.js:2402:5)
    at internalTickCallback (internal/process/next_tick.js:70:11)
    at process._tickCallback (internal/process/next_tick.js:47:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:777:11)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)

=================================================================================
```

**Comment by alexblom** [comment]
Thanks for reporting this (and for the video - very helpful!)

If you still have a repro case, do you mind telling me what the contents of corber/cordova/ and corber/cordova/config.xml?

**Comment by caiokawasaki** [comment]
Here is my config.xml file:

```
<?xml version='1.0' encoding='utf-8'?>
<widget id="br.com.robbu.invenio" version="2.0.2" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>Invenio Live</name>
    <description>
    </description>
    <content src="index.html" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <icon height="40" id="icon-40" src="res/icon/ios/icon-40.png" width="40" />
        <icon height="57" id="icon" src="res/icon/ios/icon.png" width="57" />
        <icon height="80" id="icon-40@2x" src="res/icon/ios/icon-40@2x.png" width="80" />
        <icon height="120" id="icon-40@3x" src="res/icon/ios/icon-40@3x.png" width="120" />
        <icon height="60" id="icon-60" src="res/icon/ios/icon-60.png" width="60" />
        <icon height="120" id="icon-60@2x" src="res/icon/ios/icon-60@2x.png" width="120" />
        <icon height="180" id="icon-60@3x" src="res/icon/ios/icon-60@3x.png" width="180" />
        <icon height="114" id="icon@2x" src="res/icon/ios/icon@2x.png" width="114" />
        <icon height="29" id="icon-small" src="res/icon/ios/icon-small.png" width="29" />
        <icon height="58" id="icon-small@2x" src="res/icon/ios/icon-small@2x.png" width="58" />
        <icon height="87" id="icon-small@3x" src="res/icon/ios/icon-small@3x.png" width="87" />
        <icon height="152" id="icon-76@2x" src="res/icon/ios/icon-76@2x.png" width="152" />
        <icon height="76" id="icon-76" src="res/icon/ios/icon-76.png" width="76" />
        <icon height="72" id="icon-72" src="res/icon/ios/icon-72.png" width="72" />
        <icon height="144" id="icon-72@2x" src="res/icon/ios/icon-72@2x.png" width="144" />
        <icon height="50" id="icon-50" src="res/icon/ios/icon-50.png" width="50" />
        <icon height="100" id="icon-50@2x" src="res/icon/ios/icon-50@2x.png" width="100" />
        <icon height="167" id="icon-83.5@2x" src="res/icon/ios/icon-83.5@2x.png" width="167" />
        <icon height="120" id="icon-120" src="res/icon/ios/icon-120.png" width="120" />
        <icon height="240" id="icon-120@2x" src="res/icon/ios/icon-120@2x.png" width="240" />
        <icon height="152" id="icon-152" src="res/icon/ios/icon-152.png" width="152" />
        <icon height="304" id="icon-152@2x" src="res/icon/ios/icon-152@2x.png" width="304" />
        <icon height="20" id="icon-20" src="res/icon/ios/icon-20.png" width="20" />
        <icon height="48" id="icon-24@2x" src="res/icon/ios/icon-24@2x.png" width="48" />
        <icon height="55" id="icon-27.5@2x" src="res/icon/ios/icon-27.5@2x.png" width="55" />
        <icon height="88" id="icon-44@2x" src="res/icon/ios/icon-44@2x.png" width="88" />
        <icon height="172" id="icon-86@2x" src="res/icon/ios/icon-86@2x.png" width="172" />
        <icon height="196" id="icon-98@2x" src="res/icon/ios/icon-98@2x.png" width="196" />
        <icon height="1024" id="icon-1024" src="res/icon/ios/icon-1024.png" width="1024" />
    </platform>
    <platform name="android">
        <allow-intent href="market:*" />
        <icon density="ldpi" id="ldpi" src="res/icon/android/ldpi.png" />
        <icon density="mdpi" id="mdpi" src="res/icon/android/mdpi.png" />
        <icon density="hdpi" id="hdpi" src="res/icon/android/hdpi.png" />
        <icon density="xhdpi" id="xhdpi" src="res/icon/android/xhdpi.png" />
        <icon density="xxhdpi" id="xxhdpi" src="res/icon/android/xxhdpi.png" />
        <icon density="xxxhdpi" id="xxxhdpi" src="res/icon/android/xxxhdpi.png" />
        <splash density="port-ldpi" id="port-ldpi" src="res/screen/android/port-ldpi.png" />
        <splash density="land-ldpi" id="land-ldpi" src="res/screen/android/land-ldpi.png" />
        <splash density="port-mdpi" id="port-mdpi" src="res/screen/android/port-mdpi.png" />
        <splash density="land-mdpi" id="land-mdpi" src="res/screen/android/land-mdpi.png" />
        <splash density="port-hdpi" id="port-hdpi" src="res/screen/android/port-hdpi.png" />
        <splash density="land-hdpi" id="land-hdpi" src="res/screen/android/land-hdpi.png" />
        <splash density="port-xhdpi" id="port-xhdpi" src="res/screen/android/port-xhdpi.png" />
        <splash density="land-xhdpi" id="land-xhdpi" src="res/screen/android/land-xhdpi.png" />
        <splash density="port-xxhdpi" id="port-xxhdpi" src="res/screen/android/port-xxhdpi.png" />
        <splash density="land-xxhdpi" id="land-xxhdpi" src="res/screen/android/land-xxhdpi.png" />
        <splash density="port-xxxhdpi" id="port-xxxhdpi" src="res/screen/android/port-xxxhdpi.png" />
        <splash density="land-xxxhdpi" id="land-xxxhdpi" src="res/screen/android/land-xxxhdpi.png" />
    </platform>
    <engine name="android" spec="~7.1.4" />
</widget>
```

**Comment by alexblom** [comment]
Can I suggest you delete the contents of /platforms and then re-add the platform to see if that resolves the issue - or does this happen 100% of the time you try to add?

Unfortunately sometimes you can hit a weirder state where a platform does not install 100% properly. It's something we need to look into - but the issue can cascade from there.
