### ISSUE TITLE
Linux: "corber start"  "file" argument must be a non-empty string

### ISSUE THREAD

**Issue by Mithrilhall** [isleofcode/corber#609]
**corber start** results in **"file" argument must be a non-empty string**

> ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: "file" argument must be a non-empty string
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: "file" argument must be a non-empty string
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:389:11)
    at Object.exports.spawn (child_process.js:502:38)
    at module.exports (/home/user/.nvm/versions/node/v8.15.1/lib/node_modules/corber/lib/utils/spawn.js:24:28)
    at module.exports (/home/user/.nvm/versions/node/v8.15.1/lib/node_modules/corber/lib/targets/android/tasks/list-devices.js:36:10)
    at Class.getInstalledDevices (/home/user/.nvm/versions/node/v8.15.1/lib/node_modules/corber/lib/commands/start.js:138:21)
    at Class.selectDevice (/home/user/.nvm/versions/node/v8.15.1/lib/node_modules/corber/lib/commands/start.js:90:17)
    at selectPlatforms.then (/home/user/.nvm/versions/node/v8.15.1/lib/node_modules/corber/lib/commands/start.js:210:33)
    at tryCatcher (/home/user/.nvm/versions/node/v8.15.1/lib/node_modules/corber/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/home/user/.nvm/versions/node/v8.15.1/lib/node_modules/corber/node_modules/rsvp/dist/rsvp.js:495:31)
    at publish (/home/user/.nvm/versions/node/v8.15.1/lib/node_modules/corber/node_modules/rsvp/dist/rsvp.js:481:7)

**Comment by angrybear11** [comment]
I had a similar issue using homebrew on MacOS. Make sure your `ANDROID_HOME` environment variable is set to your android-sdk path. In my case, I needed

`export ANDROID_HOME='/usr/local/share/android-sdk'`

**Comment by Mithrilhall** [comment]
Updated my _.profile_ with the following two lines:
>export ANDROID_HOME=$HOME/Android/Sdk
export PATH="$HOME/bin:$HOME/.local/bin:$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools"

That got me closer:

> user@user-ThinkPad-T460:~/source-local/corber-test$ corber start
Corber Starting
"file" argument must be a non-empty string
"file" argument must be a non-empty string


>Stack Trace and Error Report: /tmp/error.dump.12ce8aa86b41f97e3c1c7353165b3d4a.log
user@user-ThinkPad-T460:~/source-local/corber-test$

**Comment by BobrImperator** [comment]
If your SDK has been installed by android-studio then you need to add
`export ANDROID_HOME="$HOME/Android/Sdk/"`
in either your `~/.zshrc` or `~/.bashrc` depending on which one you're using.

**Comment by alexblom** [comment]
Did the advice from @BobrImperator work for you?

I'm also going through the process of setting up a spare PC here with an Ubuntu partition. Should be better to test on than parallels.

**Comment by Mithrilhall** [comment]
It looks like it almost did.

> user: ~/source-local/corber-test$ corber start
Corber Starting
? Select a device/emulator android emulator - Nexus_5X_API_28_x86
WARNING: corber 
Your corber/cordova/config.xml file has set the following flag:
        <allow-navigation href="http://10.100.100.251:4200" />
This is necessary for device live-reload to work, but is unsafe and should not be used in production.
No apk found
No apk found
user: ~/source-local/corber-test

**Comment by BobrImperator** [comment]
It's actually a problem that I also encounter, but I thought that maybe compatibility web page would help, but as turns out it's completely removed now.

**Comment by alexblom** [comment]
@Mithrilhall @BobrImperator Thanks. It looks like there are two steps to rectifying this:

- Adding the ANDROID_HOME tag.Our docs have been updated to reflect this;
- The follow on issue is covered in #613. I need to deploy a fix;

@BobrImperator For compat - start should now support all platforms. There appears to be an issue where Android APKs now have some updated locations we need to check which is better covered in #613.

Thanks!
