### ISSUE TITLE
corber init error

### ISSUE THREAD

**Issue by masato-io** [isleofcode/corber#655]
hi, I'm getting the following error when I run corber init with ember octane project. Is there any way to resolve this issue by any chance?

```
corber init
corber: updating .gitignore
corber: updating .eslintignore
Adding corber to devDependencies
Installing corber
Detected yarn.lock - using yarn
yarn add v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "@ember/jquery > ember-cli-babel > babel-plugin-debug-macros@0.2.0" has unmet peer dependency "@babel/core@^7.0.0-beta.42".
warning "ember-data > ember-cli-typescript > @babel/plugin-transform-typescript@7.4.5" has unmet peer dependency "@babel/core@^7.0.0-0".
[5/5] Building fresh packages...
success Saved lockfile.
success Saved 0 new dependencies.
Done in 3.01s.
corber: updating .watchmanconfig
Added corber to watchman ignore
Installing corber-ember-livereload
Detected yarn.lock - using yarn
yarn add v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "@ember/jquery > ember-cli-babel > babel-plugin-debug-macros@0.2.0" has unmet peer dependency "@babel/core@^7.0.0-beta.42".
warning "ember-data > ember-cli-typescript > @babel/plugin-transform-typescript@7.4.5" has unmet peer dependency "@babel/core@^7.0.0-0".
[5/5] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ corber-ember-livereload@0.0.2
info All dependencies
└─ corber-ember-livereload@0.0.2
Done in 3.27s.
? Which platforms should we init with? ios

^CWARNING: corber
corber initializes ios with the upgraded WKWebView. See http://corber.io/pages/workflow/default_webviews for details and flags
Initializing cordova with upgraded WebView cordova-plugin-wkwebview-engine
cordova-ios version not detected (lacks script /Users/rami2929/code/*shabedoko/client/corber/cordova/platforms/ios/cordova/version ), continuing.
apple-ios version not detected (lacks script /Users/rami2929/code/*shabedoko/client/corber/cordova/platforms/ios/cordova/apple_ios_version ), continuing.
Unable to load PlatformApi from platform. Error: Cannot find module '/Users/rami2929/code/*shabedoko/client/corber/cordova/platforms/ios/cordova/Api.js'
Require stack:
- /Users/rami2929/.config/yarn/global/node_modules/cordova-lib/src/cordova/util.js
- /Users/rami2929/.config/yarn/global/node_modules/cordova-lib/src/platforms/platforms.js
- /Users/rami2929/.config/yarn/global/node_modules/cordova-lib/src/plugman/install.js
- /Users/rami2929/.config/yarn/global/node_modules/cordova-lib/src/plugman/plugman.js
- /Users/rami2929/.config/yarn/global/node_modules/cordova-lib/cordova-lib.js
- /Users/rami2929/.config/yarn/global/node_modules/corber/bin/cordova-lib-runner
Failed to install 'cordova-plugin-wkwebview-engine': Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('The platform "ios" does not appear to be a valid cordova platform. It is missing API.js. ios not supported.')
    at CordovaEventEmitter.emit (events.js:304:17)
    at CordovaEventEmitter.emit (/Users/rami2929/.config/yarn/global/node_modules/cordova-common/src/events.js:69:22)
    at Object.getPlatformApiFunction (/Users/rami2929/.config/yarn/global/node_modules/cordova-lib/src/cordova/util.js:384:20)
    at Object.getPlatformApi (/Users/rami2929/.config/yarn/global/node_modules/cordova-lib/src/platforms/platforms.js:55:32)
    at handleInstall (/Users/rami2929/.config/yarn/global/node_modules/cordova-lib/src/plugman/install.js:580:29)
    at /Users/rami2929/.config/yarn/global/node_modules/cordova-lib/src/plugman/install.js:349:28
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:89365) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('The platform "ios" does not appear to be a valid cordova platform. It is missing API.js. ios not supported.')
    at CordovaEventEmitter.emit (events.js:304:17)
    at CordovaEventEmitter.emit (/Users/rami2929/.config/yarn/global/node_modules/cordova-common/src/events.js:69:22)
    at Object.getPlatformApiFunction (/Users/rami2929/.config/yarn/global/node_modules/cordova-lib/src/cordova/util.js:384:20)
    at Object.getPlatformApi (/Users/rami2929/.config/yarn/global/node_modules/cordova-lib/src/platforms/platforms.js:55:32)
    at handleInstall (/Users/rami2929/.config/yarn/global/node_modules/cordova-lib/src/plugman/install.js:580:29)
    at /Users/rami2929/.config/yarn/global/node_modules/cordova-lib/src/plugman/install.js:349:28
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:89365) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:89365) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

here is v info:
```
corber -v
corber (global): 1.4.2
corber (package.json): 1.4.2
corber (node_modules): 1.4.2
node: 13.11.0
```

**Comment by ahmacleod** [comment]
I just tried this with a clean install of corber, ember-cli, and a fresh `ember new`, and I couldn't reproduce it. Can you provide some more info about your OS?

My versions:
OSX 10.13.3
ember-cli 3.17.0
ember-source 3.17.0

```
corber -v
corber (global): 1.4.2
corber (package.json): 1.4.2
corber (node_modules): 1.4.2
node: 13.12.0
```
