### ISSUE TITLE
xctrace not in path with Xcode 12.5.1

### ISSUE THREAD

**Issue by XuluWarrior** [isleofcode/corber#701]
Changes in #698 mean that running `corber start --platform=ios` tries to run `/usr/bin/xctrace`.

However,  although I've recently just updated to Xcode 12.5.1 and `xctrace` is in `/Applications/Xcode.app/Contents/Developer/usr/bin` it is not in `/usr/bin`.

And so I get the following exception
```
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/bin/xctrace ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /usr/bin/xctrace',
  path: '/usr/bin/xctrace',
  spawnargs: [ 'list', 'devices' ]
}
```

Although it's not mentioned in http://corber.io/pages/ios-setup.html, I wonder if I also need to install the Xcode command line tools.

Or seeing that corber relies on the Xcode IDE being installed, maybe it should be running `xctrace` from its location in `Xcode.app`?

**Comment by XuluWarrior** [comment]
I tried updating to XCode 13.2.1 and also updating my Command Line Tools to 13.2 but I still don't have `xtrace` in my path.
I am wondering if the Monterey upgrade installs `xcode` to `/usr/bin`.  (I'm running Big Sur 11.6.2)
